\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{notes}[2013/02/07 v0.1 Notes]

\LoadClass[12pt,a4paper,twocolumn]{article}

\RequirePackage[latin1]{inputenc}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{graphicx}
\RequirePackage{epstopdf}
\RequirePackage{times}
\RequirePackage[hmargin={1cm,1cm},vmargin={2cm,2cm}]{geometry}
\RequirePackage{natbib}
%% \RequirePackage{siunitx}

\setlength{\parindent}{0pt}
\setlength{\parskip}{2ex}
\setlength{\columnsep}{4ex}

\endinput
